config/routes.rb
Rails.application.routes.draw do
  get  'welcome/index'
  root 'welcome#index'
  get  'catalog/index'
  get  'category/show'
  get  'electronics/index'
  get  'clothes/index'

end

app/models/attributes_name.rb
class AttributesName < ActiveRecord::Base
end

app/models/attributes_value.rb
class AttributesValue < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  scope :main, -> { where(parent_id: 0) }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  self.table_name = 'supply'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :main_menu_categories

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception







  private

  def main_menu_categories
    @categories = []
    Category.main.each do |main_category|
      sub_categories = []
        Category.where(parent_id: main_category.id).each do |sub_category|
        sub_categories << [sub_category.name, sub_category.id]
      end
      @categories << [[main_category.name, main_category.id], sub_categories]
    end
    top_menu
  end

  def top_menu
    @categories_top = @categories[0..8]
    @categories_top.each do |category|
      category[1] = category[1][0..8] if category[1].length > 8
    end
    # @categories_top << [['Ещё', 0], @categories[9..-1].transpose[0]]
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  before_action :catalog_menu



  private


  def catalog_menu
    @categories_catalog = @categories[0..11]
    @categories_catalog.each do |category|
      category[1] = category[1][0..6] if category[1].length > 8
    end
  end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def show
    category_id    = params[:category_id]
    @category_name = params[:category_name]
    sub_categories_define(category_id)
  end

  private

  def sub_categories_define(category_id)
    @sub_categories = []
    Category.where(parent_id: category_id).each do |sub_category|
      sub_sub_categories = []
      Category.where(parent_id: sub_category.id).each do |sub_sub_category|
        sub_sub_categories << [sub_sub_category.name, sub_sub_category.id, sub_sub_category.electronics_like]
      end
      more_sub_sub_categories = nil
      if sub_sub_categories.length > 5
        more_sub_sub_categories = sub_sub_categories[5..-1]
        sub_sub_categories = sub_sub_categories[0..4]
      end
      @sub_categories << [[sub_category.name, sub_category.id, sub_category.electronics_like],
                          sub_sub_categories, more_sub_sub_categories]
    end
  end

end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController

  def index
    @category_id = params[:category_id]
    @products = Product.paginate(:page => params[:page], :per_page => 8).where(category_id: @category_id)
                    .select(:id, :name)
    products_ids = @products.map{ |p| p.id }
    @photos = Photo.where(product_id: products_ids, first: true).select(:product_id, :url).to_a
    attributes_name = AttributesName.find_by(category_id: @category_id, name: 'Цвет')
    @attributes_values = AttributesValue.where(product_id: products_ids, attributes_names_id: attributes_name)
                             .select(:product_id, :value).to_a
    @supply = Supply.where(product_id: products_ids).select(:product_id, :price).to_a
  end

end

app/controllers/electronics_controller.rb
class ElectronicsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/electronics_helper.rb
module ElectronicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/catalog/index.html.erb
<%= render 'welcome/welcome_nav' %>

<div class="row">
  <div class="col-md-2"></div>
    <% i = -1 %>
    <!--3.times do -->
      <% 4.times do %>
        <% i += 1 %>
        <div class="col-md-2">
          <h4>
            <%= link_to @categories_catalog[i][0][0],
                          category_show_path(category_name: @categories_catalog[i][0][0],
                                               category_id: @categories_catalog[i][0][1]),
                          class: 'main-category' %>
          </h4>
          <% @categories_catalog[i][1].each do |sub_category| %>
            <%= link_to sub_category[0], category_show_path(category_name: sub_category[0],
                                                              category_id: sub_category[1]) %>
            <span>*</span>
          <% end %>
          <div class="all-link">
            <%= link_to "Вся/все #{@categories_catalog[i][0][0]} >",
                          category_show_path(category_category: @categories_catalog[i][0][0],
                                                   category_id: @categories_catalog[i][0][1]),
                          class: 'all-link' %>
          </div>
        </div>
      <% end %>
    <!--end -->
  <div class="col-md-2"></div>
</div>

app/views/category/show.html.erb
<div class="welc-nav">
  <%= @category_name %>
</div>
<div class="welc-descr"></div>
<hr class="hor-line-welc">

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-2">
    <% @sub_categories.each do |sub_category| %>
      <h4>
        <% case sub_category[0][2]%>
          <% when true %>
            <%= link_to sub_category[0][0],
                        electronics_index_path(category_id: sub_category[0][1], page_number: 1),
                        class: 'main-category' %>
          <% when false %>
            <%= link_to sub_category[0][0],
                        clothes_index_path(category_id: sub_category[0][1], page_number: 1),
                        class: 'main-category' %>
          <% when nil %>
            <%= link_to sub_category[0][0],
                        category_show_path(category_id: sub_category[0][1]),
                        class: 'main-category category-show' %>
        <% end %>
      </h4>
      <% if !sub_category[1].empty? %>
        <% sub_category[1].each do |sub_sub_category| %>
          <% case sub_category[0][2]%>
            <% when true %>
              <%= link_to sub_sub_category[0],
                          electronics_index_path(category_id: sub_sub_category[1], page_number: 1) %>
            <% when false %>
              <%= link_to sub_sub_category[0],
                          clothes_index_path(category_id: sub_sub_category[1], page_number: 1) %>
            <% when nil %>
              <%= link_to sub_sub_category[0],
                          category_show_path(category_name: sub_sub_category[0],
                                             category_id: sub_sub_category[1]),
                          class: 'category-show' %>
          <% end %>
          </br>
        <% end %>
        <% if sub_category[2] %>
          <span class="all-list">
            <% sub_category[2].each do |more_sub_sub_category| %>
              <% case sub_category[0][2]%>
                <% when true %>
                  <%= link_to more_sub_sub_category[0],
                          electronics_index_path(category_id: more_sub_sub_category[1], page_number: 1) %>
                <% when false %>
                  <%= link_to more_sub_sub_category[0],
                          clothes_index_path(category_id: more_sub_sub_category[1], page_number: 1) %>
                <% when nil %>
                  <%= link_to more_sub_sub_category[0],
                          category_show_path(category_name: more_sub_sub_category[0],
                                             category_id: more_sub_sub_category[1]),
                          class: 'category-show' %>
              <% end %>
              </br>
            <% end %>
          </span>
          <span>
            <%= link_to "Ещё v", "#", class: "all-link" %>
          </span>
        <% end %>
        </br>
      <% end %>
      <hr>
    <% end %>
  </div>

</div>

app/views/clothes/_clothes.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-3">
      <span>
        <% photo = @photos.find{ |photo| photo.product_id == product.id }.url %>
        <% if photo %>
            <%= image_tag(photo) %>
        <% else %>
            <%= image_tag("camera-no-image.jpg") %>
        <% end %>
      </span></br>
      <span><%= product.name %></span></br>
      <span>
        <% attributes = @attributes_values.find_all{ |attr| attr.product_id == product.id } %>
        <% attributes.each do |attr| %>
            <%= attr.value %>
        <% end %>
      </span></br>
      <span><%= @supply.find{ |photo| photo.product_id == product.id }.price %></span></br></br>
    </div>
  <% end %>
</div>
</br>
<span>
  <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
</span>

app/views/clothes/_menu.html.erb
menu

app/views/clothes/index.html.erb
</br>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-2">
        <%= render 'menu' %>
      </div>
      <div class="col-md-10 sort_paginate_ajax" >
        <%= render 'clothes' %>
      </div>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/clothes/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("clothes"))%>")

app/views/layouts/_top_navigation.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <!-- The mobile navbar-toggle button can be safely removed since you do not need it in a non-responsive implementation -->
      <%= link_to 'Яндекс', root_path, class: 'navbar-brand' %>
    </div>
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Найти</button>
    </form>
    <div class="navbar-right">
      <%= link_to 'Мой маркет', root_path, class: 'btn btn-default' %>
      <%= link_to '', root_path, class: 'glyphicon glyphicon-th' %>
      <%= link_to 'Войти', root_path, class: 'btn btn-default' %>
    </div>
  </div>
  <hr class="hor-line-top">
  <div class="container">

    <!-- Note that the .navbar-collapse and .collapse classes have been removed from the #navbar -->
    <div id="navbar">
      <ul class="nav navbar-nav dropdown">
        <% @categories_top.each do |category| %>
            <li class="dropdown-top">
              <%= link_to category[0][0],
                          category_show_path(category_name: category[0][0],
                                               category_id: category[0][1]),
                          class: 'dropdown-toggle',
                          'data-toggle' => 'dropdown',
                          role: 'button',
                          'aria-haspopup' => true,
                          'aria-expanded' => false  %>
              <ul class="dropdown-menu dropdown-inside">
                <% category[1].each do |sub_category| %>
                  <li>
                    <%= link_to sub_category[0],
                                category_show_path(category_name: sub_category[0],
                                                     category_id: sub_category[1]) %>
                  </li>
                <% end %>
              </ul>
            </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>YandexMarket</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render 'layouts/top_navigation' %>


  <%= yield %>

</body>
</html>

app/views/welcome/_welcome_nav.html.erb
<div class="welc-nav">
  <%= link_to 'Витрина', root_path %><span class="tab-welc-nav"></span>
  <%= link_to 'Каталог', catalog_index_path %></br>
</div>
<div class="welc-descr">
  <span>Новинки, скидки, рекомендации</span><span class="tab-welc-descr"></span>
  <span>Более 1500 категорий товаров</span>
</div>
<hr class="hor-line-welc">

app/views/welcome/index.html.erb
<%= render 'welcome/welcome_nav' %>